apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dns-internal-service-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dns-internal-service-cr
subjects:
- kind: ServiceAccount
  name: dns-internal-sa
  namespace: dev
