apiVersion: v1
data:
  kuberhealthy.yaml: |-
    listenAddress: ":8080" # The port for kuberhealthy to listen on for web requests
    enableForceMaster: false # Set to true to enable local testing, forced master mode
    logLevel: error # Log level to be used (default: debug)
    influxUsername: "" # Username for the InfluxDB instance
    influxPassword: "" # Password for the InfluxDB instance
    influxURL: "" # Address for the InfluxDB instance
    influxDB: "http://localhost:8086" # Name of the InfluxDB database
    enableInflux: false # Set to true to enable metric forwarding to Infux DB
    maxKHJobAge: 15m
    maxCheckPodAge: 72h
    maxCompletedPodCount: 4
    maxErrorPodCount: 4
    stateMetadata:
kind: ConfigMap
metadata:
  name: kuberhealthy
  namespace: dev
